# Generated by Django 3.1.7 on 2021-05-15 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210513_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_by', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='blog.post')),
            ],
        ),
    ]
