# Generated by Django 3.1.7 on 2021-05-16 00:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_share_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='time_shared',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
